accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout')
]

django_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('event.urls')),
    path('first-module/', include('first_module.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index')
]

first_module/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('add', views.add, name='add')

]

accounts/models.py
from django.db import models

# Create your models here.

event/models.py
from django.db import models
from datetime import datetime
# Create your models here.


class Event(models.Model):
    title = models.TextField()
    description = models.TextField(default=None)
    date = models.DateField(null=True, blank=True, default=None)
    img = models.ImageField(upload_to='pics')
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.now, blank=True)

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User, auth
from django.contrib import messages

# Create your views here.


def register(request):
    if request.method == 'POST':
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        con_password = request.POST['con_password']
        if password == con_password:
            if User.objects.filter(email=email).exists():
                messages.info(request, "Email already exists !")
                return redirect('accounts:register')
            else:
                user = User.objects.create_user(username=username, first_name=firstname, last_name=lastname, email=email, password=password)
                user.save()
                messages.info(request, "Registration Successful. Please login ")
                return redirect('accounts:login')
        else:
            messages.info(request, "Password does not match")
            return redirect('accounts:register')
    else:
        return render(request, 'register.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            print("User authenticated")
            auth.login(request, user)
            return redirect('add')
        else:
            print("User not authenticated")
            messages.info(request, "Password does not match")
            return redirect('accounts:login')
    else:
        return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

event/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Event

# Create your views here.


def index(request):
    events = Event.objects.all()
    return render(request, 'index.html', {'events': events})

first_module/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def home(request):
    return render(request, 'home.html', {'name': 'Kamrul Hasan'})


def add(request):
    if request == 'POST':
        val1 = int(request.POST['num1'])
        val2 = int(request.POST['num2'])
        result = val1 + val2
        return render(request, 'result.html', {'result': result})
    else:
        return render(request, 'home.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>ToDo || Admin</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body  style="background-color:#E5E1EA">

<div class="container">
    {% block content %}
    {% endblock %}

</div>

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
<h2>First Test Form</h2>
  <form action="add" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="email">Num 1:</label>
      <input type="number" class="form-control" id="email" placeholder="Enter email" name="num1">
    </div>
    <div class="form-group">
      <label for="pwd">Num 2:</label>
      <input type="number" class="form-control" id="pwd" placeholder="Enter password" name="num2">
    </div>
    <div class="form-group form-check">
      <label class="form-check-label">
        <input class="form-check-input" type="checkbox" name="remember"> Remember me
      </label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

templates/index.html
{% load static %}
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Django Todo</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon"
          href="https://1card.com.bd/wp-content/uploads/2017/10/card-e1507540279484.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/meanmenu.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/default.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
</head>
<body>
<!-- header-start -->
<header class="header-transparent">
    <div id="sticky-header" class="main-menu-area pt-40" style="background-color:#e61937">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-lg-3">
                    <div class="logo">
                        <a href="#"><img src="{% static 'img/logo/onecard_logo.png' %}" alt=""/></a>
                    </div>
                </div>
                <div class="col-xl-9 col-lg-9">
                    <div class="main-menu text-right f-right">
                        <nav id="mobile-menu">
                            <ul>
                                <li><a href="#">HOME </a></li>
                                <li><a target="_blank" href="https://1card.com.bd/">ABOUT US</a></li>
                                <li><a href="#">EVENTS</a></li>
                                {% if user.is_authenticated %}
                                <li><a href="{% url 'accounts:logout' %}">logout</a></li>
                                {% else %}
                                <li><a href="{% url 'accounts:register' %}">Register</a></li>
                                <li><a href="{% url 'accounts:login' %}">login</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-12">
                    <div class="mobile-menu"></div>
                </div>
            </div>
        </div>
    </div>
    <!-- Extra leftside Pop up window -->

</header>

<div class="events-area pt-120" id="events" style="margin-top: 42px;">
    <div class="container">

        <div class="row">

            {% for event in events %}

            <div class="col-xl-6 col-lg-6 col-md-6">
                <div class="events-wrapper text-center mb-60">
                    <div class="events-img" style="border: 1px solid black;border-radius: 5px">
                        <a href="event-detail-id">
                            <img src="{{ event.img.url }}" alt="Event Photo" height="250"
                                 style="border-radius: 5px"/>
                        </a>
                    </div>
                    <div class="events-meta">
                        <span>Registration till {{ event.date }}</span>
                    </div>
                    <div class="events-text">
                        {% if event.title == "pic1" %}
                        <h3><a href="event-detail-id">extra if condition</a></h3>
                        {% endif %}
                        <h3><a href="event-detail-id">{{ event.title }}</a></h3>
                        <p>{{ event.description }}</p>
                        <a class="btn" href="event-detail-id">Join Now</a>
                    </div>
                </div>
            </div>

            {% endfor %}

        </div>
    </div>
</div>
<footer>
    <div class="footer-bottom-area pt-25 pb-25">
        <div class="container">
            <div class="row">
                <div class="col-xl-6 col-lg-6">
                    <div class="copyright">
                        <p><i class="far fa-copyright"></i> 2021 Daffodil Computers Ltd. All Rights Reserved. Developed
                            By <a href="https://www.linkedin.com/in/kamrulhasan0101" target="_blank">Kamrul Hasan.</a>
                        </p>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6">
                    <ul class="footer-footer-link text-lg-right">
                        <li><a href="http://1card.com.bd/" target="_blank">1 Card </a></li>
                        <li><a href="http://daffodilvarsity.edu.bd/" target="_blank"> DIU </a></li>
                        <li><a href="https://1card.com.bd/about-us/contact-us/" target="_blank"> Contact Us </a></li>
                        <li><a href="#">Event Portal</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- JS here -->
<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'js/jquery.meanmenu.min.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/ajax-form.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
<script src="{% static '/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% block content %}
    <br>
    <h2 class="text-center">Login form</h2>
    <hr>
    <div class="row">
        {% if messages %}
        <h4>Please resolve these issues</h4>
        {% endif %}

        <ul>
            {% for message in messages %}
            <li style="color:red">{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    <form action="login" method="post">
        {% csrf_token %}

        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 col-form-label">User Name</label>
            <div class="col-sm-10">
                <input type="text" name="username" class="form-control" id="inputEmail3" placeholder="User Name">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
            <div class="col-sm-10">
                <input type="password" name="password" class="form-control" id="inputPassword3" placeholder="Password">
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-10 text-right">
                <a href="{% url 'accounts:register' %}">Did not register yet? click to register.</a> <button type="submit" class="btn btn-primary">Login</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block content %}
    <br>
    <h2 class="text-center">Registration form</h2>
    <hr>
    <div class="row">
        {% if messages %}
        <h4>Please resolve these issues</h4>
        {% endif %}

        <ul>
            {% for message in messages %}
            <li style="color:red">{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    <form action="register" method="post">
        {% csrf_token %}
        <div class="form-group row">
            <label for="firstName3" class="col-sm-2 col-form-label">First Name</label>
            <div class="col-sm-10">
                <input type="text" name="firstname" class="form-control" id="firstName3" placeholder="First Name">
            </div>
        </div>
        <div class="form-group row">
            <label for="lastName3" class="col-sm-2 col-form-label">Last Name</label>
            <div class="col-sm-10">
                <input type="text" name="lastname" class="form-control" id="lastName3" placeholder="Last Name">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputUserName3" class="col-sm-2 col-form-label">User Name</label>
            <div class="col-sm-10">
                <input type="text" name="username" class="form-control" id="inputUserName3" placeholder="User Name">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
            <div class="col-sm-10">
                <input type="email" name="email" class="form-control" id="inputEmail3" placeholder="Email">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
            <div class="col-sm-10">
                <input type="password" name="password" class="form-control" id="inputPassword3" placeholder="Password">
            </div>
        </div>

        <div class="form-group row">
            <label for="inputConPassword3" class="col-sm-2 col-form-label">Confirm Password</label>
            <div class="col-sm-10">
                <input type="password" name="con_password" class="form-control" id="inputConPassword3"
                       placeholder="Confirm Password">
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-10 text-right">
             <a href="{% url 'accounts:login' %}">Already registered? click to login.</a>   <button type="submit" class="btn btn-primary">Sign UP</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/result.html
{% extends 'base.html' %}
{% block content %}
<h2> The result is : {{ result }}</h2>
{% endblock %}